name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
      test:
        runs-on: ubuntu-latest
        name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
        strategy:
          matrix:
            otp: ['25.3']
            elixir: ['1.14']
        env:
          MIX_ENV: "test"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
          - uses: actions/checkout@v3
          - uses: erlef/setup-beam@v1
            id: beam
            with:
              otp-version: ${{matrix.otp}}
              elixir-version: ${{matrix.elixir}}

          - name: Restore PLT/dependencies cache
            id: deps_plt_cache
            uses: actions/cache/restore@v3
            with:
              key: |
                deps_plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
              restore-keys: |
                deps_plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-
              path: |
                deps
                priv/plts

          - name: Fetch Dependencies
            if: steps.deps_plt_cache.outputs.cache-hit != 'true'
            run: |
              mix do deps.get, deps.compile
          - name: Create PLTs
            if: steps.deps_plt_cache.outputs.cache-hit != 'true'
            run: |
              mix dialyzer --plt

          - name: Save PLT/dependencies cache
            id: deps_cache_save
            uses: actions/cache/save@v3
            if: steps.deps_plt_cache.outputs.cache-hit != 'true'
            with:
              key: |
                deps_plt-${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
              path: |
                deps
                priv/plts

          - name: Compile (warning as errors)
            run: |
              mix compile --warnings-as-errors

          - name: Format
            if: ${{ matrix.elixir == '1.14' }}
            run: |
              mix format --check-formatted

          - name: Credo
            run: |
              mix credo --all --strict

          - name: Dialyzer
            run: |
              mix dialyzer --format github

          - name: Mix test
            run: |
              mix test --preload-modules --warnings-as-errors

          - name: Excoveralls
            run: |
             mix coveralls.github
